#pragma once

// Every Model 2 texture region becomes a real GPU texture (opus55, 22/09/2026).
//
// The board keeps all its textures in two 2048x1024 sheets of 4-bit texels. Sampled from the
// sheet, the texture unit can neither repeat a tile on itself (the road), nor use mipmaps, nor
// filter anisotropically: the shader had to redo it by hand, and that was the single biggest
// cost of a pixel (measured: +4 ms of ~9 ms, both eyes, 1680x1760, MSAA 4x).
//
// Here each region (sheet, x, y, w, h) that a polygon uses gets its own VkImage with a full mip
// chain generated by the GPU, sampled with REPEAT / MIRRORED_REPEAT and hardware anisotropy,
// all indexed from ONE descriptor array by a per-polygon slot (VK_EXT_descriptor_indexing).
//
// What is stored is NOT a colour: it is the raw texel t (and, for cut-outs, t premultiplied by
// opacity plus the opacity). The polygon's palette / tone curve is applied AFTER filtering, in
// the shader, exactly like the board -- so one image per texture, whatever palette uses it.
//   R = t*17            (opaque use: t = R*15)
//   G = t*17 * opaque   B = 255 * opaque   (cut-out use: t = G/B*15, alpha = B), opaque = t != 15
//
// Texture RAM is static during a race (measured: 0 writes after loading), so a region is built
// once and kept until the sheets change.

#include <vulkan/vulkan.h>
#include <unordered_map>
#include <vector>
#include <set>
#include <string>
#include <cstdio>
#include <cstring>
#include <algorithm>

#include "vulkan_utils.h"

namespace arcadexr::vulkan {

class M2RegionTextures {
public:
    static constexpr uint32_t kMaxSlots = 512;
    static constexpr uint32_t kNone = 0xffffu;
    static constexpr uint32_t kStagingBytes = 16u * 1024u * 1024u;
    // Two halves, alternated per frame: a frame's regions are written while the GPU may still
    // be copying the previous frame's from the other half (the plugin builds before the fence).
    static constexpr uint32_t kHalfBytes = kStagingBytes / 2;

    void Init(VkDevice device, const MemoryAllocator* alloc, float maxAniso) {
        m_dev = device;
        m_alloc = alloc;
        m_maxAniso = maxAniso;
        for (int m = 0; m < 8; ++m) {
            VkSamplerCreateInfo si{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};
            si.magFilter = VK_FILTER_LINEAR;
            si.minFilter = VK_FILTER_LINEAR;
            si.mipmapMode = VK_SAMPLER_MIPMAP_MODE_LINEAR;
            si.addressModeU = (m & 1) ? VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT : VK_SAMPLER_ADDRESS_MODE_REPEAT;
            si.addressModeV = (m & 2) ? VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT : VK_SAMPLER_ADDRESS_MODE_REPEAT;
            si.addressModeW = VK_SAMPLER_ADDRESS_MODE_REPEAT;
            si.anisotropyEnable = (maxAniso > 1.0f && m < 4) ? VK_TRUE : VK_FALSE;   // [4..7]: same, no anisotropy
            si.maxAnisotropy = std::max(1.0f, maxAniso);
            si.minLod = 0.0f;
            si.maxLod = 16.0f;
            XRC_CHECK_THROW_VKCMD(vkCreateSampler(m_dev, &si, nullptr, &m_samplers[m]));
        }
        {   // nearest sampler for the colour table (combined image sampler, binding 14)
            VkSamplerCreateInfo si{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};
            si.magFilter = VK_FILTER_NEAREST; si.minFilter = VK_FILTER_NEAREST;
            si.mipmapMode = VK_SAMPLER_MIPMAP_MODE_NEAREST;
            si.addressModeU = si.addressModeV = si.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
            XRC_CHECK_THROW_VKCMD(vkCreateSampler(m_dev, &si, nullptr, &m_lutSampler));
        }
        // Staging, host visible, reused every frame (the previous frame's copies are fenced).
        VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};
        bi.size = kStagingBytes;
        bi.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
        XRC_CHECK_THROW_VKCMD(vkCreateBuffer(m_dev, &bi, nullptr, &m_staging));
        VkMemoryRequirements req{};
        vkGetBufferMemoryRequirements(m_dev, m_staging, &req);
        m_alloc->Allocate(req, &m_stagingMem);
        XRC_CHECK_THROW_VKCMD(vkBindBufferMemory(m_dev, m_staging, m_stagingMem, 0));
        XRC_CHECK_THROW_VKCMD(vkMapMemory(m_dev, m_stagingMem, 0, kStagingBytes, 0, reinterpret_cast<void**>(&m_stagingPtr)));
        // Dummy 1x1 image for every empty slot (no partially-bound descriptors needed).
        m_dummy = CreateImage(1, 1, 1);
        m_dummyPending = true;
        m_lut = CreateImage(64, 32, 1);
        CreateArray();
        {   // zeros until the first real table, so the image is always valid to bind
            std::vector<uint8_t> z(64 * 32 * 4, 0);
            SetLut(z.data());
        }
    }

    void Destroy() {
        if (m_dev == VK_NULL_HANDLE) return;
        Clear();
        DestroyEntry(m_dummy);
        DestroyEntry(m_lut);
        if (m_array.view) vkDestroyImageView(m_dev, m_array.view, nullptr);
        if (m_array.image) vkDestroyImage(m_dev, m_array.image, nullptr);
        if (m_array.mem) vkFreeMemory(m_dev, m_array.mem, nullptr);
        m_array = Entry{};
        if (m_arraySampler) { vkDestroySampler(m_dev, m_arraySampler, nullptr); m_arraySampler = VK_NULL_HANDLE; }
        for (auto& s : m_samplers) if (s) { vkDestroySampler(m_dev, s, nullptr); s = VK_NULL_HANDLE; }
        if (m_lutSampler) { vkDestroySampler(m_dev, m_lutSampler, nullptr); m_lutSampler = VK_NULL_HANDLE; }
        if (m_stagingPtr) { vkUnmapMemory(m_dev, m_stagingMem); m_stagingPtr = nullptr; }
        if (m_staging) vkDestroyBuffer(m_dev, m_staging, nullptr);
        if (m_stagingMem) vkFreeMemory(m_dev, m_stagingMem, nullptr);
        m_staging = VK_NULL_HANDLE; m_stagingMem = VK_NULL_HANDLE;
        m_dev = VK_NULL_HANDLE;
    }

    // Drop every region (the sheets changed). Caller guarantees the GPU is idle on them.
    void Clear() {
        for (auto& e : m_slots) DestroyEntry(e);
        m_slots.clear();
        m_map.clear();
        m_layerMap.clear();
        m_layerCount = 0;
        m_pendingLayers.clear();
        m_pending.clear();
        m_dirtySlots.clear();
        m_refillSlots.clear(); m_refillLayers.clear();
        m_resetDescriptors = true;
        m_stagingUsed = 0;
        m_lutPending = false;
    }

    // Slot of a region, creating it (this frame, within the staging budget) if new.
    // Returns kNone while it is not ready -- the shader then takes the sheet path.
    uint32_t Slot(const std::vector<uint8_t>* sheets, uint32_t sheet, uint32_t ox, uint32_t oy, uint32_t w, uint32_t h) {
        if (w < 1 || h < 1 || w > 1024 || h > 1024 || sheets[sheet & 1].empty()) return kNone;
        const uint64_t key = (uint64_t(sheet & 1) << 60) | (uint64_t(ox) << 44) | (uint64_t(oy) << 28) | (uint64_t(w) << 14) | uint64_t(h);
        auto it = m_map.find(key);
        if (it != m_map.end()) return it->second;
        if (m_slots.size() >= kMaxSlots) return kNone;
        const size_t bytes = size_t(w) * h * 4;
        if (m_stagingUsed + bytes > kHalfBytes) return kNone;  // next frame
        // Texels of the region, through the board's fold (x >= 1024 -> other half).
        uint8_t* dst = m_stagingPtr + Base() + m_stagingUsed;
        const std::vector<uint8_t>& cpu = sheets[sheet & 1];
        for (uint32_t y = 0; y < h; ++y)
            for (uint32_t x = 0; x < w; ++x) {
                int x2 = int(ox + x), y2 = int(oy + y);
                if (x2 >= 1024) { x2 -= 1024; y2 ^= 1024; }
                const size_t at = size_t(y2) * 1024 + size_t(x2);
                const uint8_t t = at < cpu.size() ? cpu[at] : 0;
                const bool opaque = t != 15;
                uint8_t* px = dst + (size_t(y) * w + x) * 4;
                px[0] = uint8_t(t * 17);
                px[1] = opaque ? uint8_t(t * 17) : 0;
                px[2] = opaque ? 255 : 0;
                px[3] = 255;
            }
        uint32_t levels = 1;
        while ((std::max(w, h) >> levels) > 0) ++levels;
        Entry e = CreateImage(w, h, levels);
        const uint32_t slot = uint32_t(m_slots.size());
        m_slots.push_back(e);
        m_map.emplace(key, slot);
        m_pending.push_back({slot, Base() + m_stagingUsed});
        m_dirtySlots.push_back(slot);
        m_stagingUsed += (bytes + 255) & ~size_t(255);
        return slot;
    }

    // ---- Texture ARRAY path (opus55, second step). The descriptor-indexed images above cost ~3 ms
    // per frame for the texture INSTRUCTION itself (measured on a frozen scene: a constant-coordinate
    // sample through the bindless path costs as much as the real one). One ordinary sampler2DArray
    // bound normally is the cheap path: the layer is just a coordinate. Every region up to 256x256
    // gets one 256x256 layer, filled by TILING the region, so the hardware REPEAT of the layer is
    // exactly the region's own repeat, and GPU mips of the tiled layer are the region's mips.
    static constexpr uint32_t kLayerSize = 256;
    static constexpr uint32_t kMaxLayers = 192;

    uint32_t Layer(const std::vector<uint8_t>* sheets, uint32_t sheet, uint32_t ox, uint32_t oy, uint32_t w, uint32_t h) {
        if (w < 1 || h < 1 || w > kLayerSize || h > kLayerSize || (kLayerSize % w) || (kLayerSize % h) || sheets[sheet & 1].empty())
            return kNone;
        const uint64_t key = (uint64_t(sheet & 1) << 60) | (uint64_t(ox) << 44) | (uint64_t(oy) << 28) | (uint64_t(w) << 14) | uint64_t(h);
        auto it = m_layerMap.find(key);
        if (it != m_layerMap.end()) return it->second;
        if (m_layerCount >= kMaxLayers || m_array.image == VK_NULL_HANDLE) return kNone;
        const size_t bytes = size_t(kLayerSize) * kLayerSize * 4;
        if (m_stagingUsed + bytes > kHalfBytes) return kNone;
        uint8_t* dst = m_stagingPtr + Base() + m_stagingUsed;
        const std::vector<uint8_t>& cpu = sheets[sheet & 1];
        for (uint32_t y = 0; y < kLayerSize; ++y)
            for (uint32_t x = 0; x < kLayerSize; ++x) {
                int x2 = int(ox + (x % w)), y2 = int(oy + (y % h));
                if (x2 >= 1024) { x2 -= 1024; y2 ^= 1024; }
                const size_t at = size_t(y2) * 1024 + size_t(x2);
                const uint8_t t = at < cpu.size() ? cpu[at] : 0;
                const bool opaque = t != 15;
                uint8_t* px = dst + (size_t(y) * kLayerSize + x) * 4;
                px[0] = uint8_t(t * 17);
                px[1] = opaque ? uint8_t(t * 17) : 0;
                px[2] = opaque ? 255 : 0;
                px[3] = 255;
            }
        const uint32_t layer = m_layerCount++;
        m_layerMap.emplace(key, layer);
        m_pendingLayers.push_back({layer, Base() + m_stagingUsed});
        m_stagingUsed += bytes;
        return layer;
    }
    uint32_t LayerCount() const { return m_layerCount; }

    // ---- Partial texture updates (24/09, Super GT 24h rewrites a few texture blocks EVERY frame; clearing all
    // regions and rebuilding the frame each time cost ~35 ms). The regions and layers that read a rewritten row
    // are re-filled in place, in the staging budget of this frame; the rest waits for the next frame.
    void InvalidateRows(uint32_t sheet, const std::vector<uint8_t>& rowDirty) {
        auto touches = [&](uint64_t key) {
            if (((key >> 60) & 1u) != (sheet & 1u)) return false;
            const uint32_t ox = uint32_t(key >> 44) & 0xffffu, oy = uint32_t(key >> 28) & 0xffffu;
            const uint32_t w = uint32_t(key >> 14) & 0x3fffu, h = uint32_t(key) & 0x3fffu;
            for (uint32_t y = oy; y < oy + h; ++y) {
                if (ox < 1024 && y < rowDirty.size() && rowDirty[y]) return true;
                if (ox + w > 1024 && (y ^ 1024u) < rowDirty.size() && rowDirty[y ^ 1024u]) return true;
            }
            return false;
        };
        for (const auto& kv : m_map) if (touches(kv.first)) m_refillSlots.insert(kv.first);
        for (const auto& kv : m_layerMap) if (touches(kv.first)) m_refillLayers.insert(kv.first);
    }
    void ProcessRefills(const std::vector<uint8_t>* sheets) {
        auto decode = [](uint64_t key, uint32_t& sh, uint32_t& ox, uint32_t& oy, uint32_t& w, uint32_t& h) {
            sh = uint32_t(key >> 60) & 1u; ox = uint32_t(key >> 44) & 0xffffu; oy = uint32_t(key >> 28) & 0xffffu;
            w = uint32_t(key >> 14) & 0x3fffu; h = uint32_t(key) & 0x3fffu;
        };
        auto texel = [](const std::vector<uint8_t>& cpu, uint32_t ox, uint32_t oy, uint32_t x, uint32_t y, uint8_t* px) {
            int x2 = int(ox + x), y2 = int(oy + y);
            if (x2 >= 1024) { x2 -= 1024; y2 ^= 1024; }
            const size_t at = size_t(y2) * 1024 + size_t(x2);
            const uint8_t t = at < cpu.size() ? cpu[at] : 0;
            const bool opaque = t != 15;
            px[0] = uint8_t(t * 17); px[1] = opaque ? uint8_t(t * 17) : 0; px[2] = opaque ? 255 : 0; px[3] = 255;
        };
        for (auto it = m_refillLayers.begin(); it != m_refillLayers.end();) {
            auto lm = m_layerMap.find(*it);
            if (lm == m_layerMap.end()) { it = m_refillLayers.erase(it); continue; }
            const size_t bytes = size_t(kLayerSize) * kLayerSize * 4;
            if (m_stagingUsed + bytes > kHalfBytes) break;
            uint32_t sh, ox, oy, w, h; decode(*it, sh, ox, oy, w, h);
            uint8_t* dst = m_stagingPtr + Base() + m_stagingUsed;
            for (uint32_t y = 0; y < kLayerSize; ++y)
                for (uint32_t x = 0; x < kLayerSize; ++x) texel(sheets[sh], ox, oy, x % w, y % h, dst + (size_t(y) * kLayerSize + x) * 4);
            m_pendingLayers.push_back({lm->second, Base() + m_stagingUsed});
            m_stagingUsed += bytes;
            it = m_refillLayers.erase(it);
        }
        for (auto it = m_refillSlots.begin(); it != m_refillSlots.end();) {
            auto sm = m_map.find(*it);
            if (sm == m_map.end()) { it = m_refillSlots.erase(it); continue; }
            uint32_t sh, ox, oy, w, h; decode(*it, sh, ox, oy, w, h);
            const size_t bytes = size_t(w) * h * 4;
            if (m_stagingUsed + bytes > kHalfBytes) break;
            uint8_t* dst = m_stagingPtr + Base() + m_stagingUsed;
            for (uint32_t y = 0; y < h; ++y)
                for (uint32_t x = 0; x < w; ++x) texel(sheets[sh], ox, oy, x, y, dst + (size_t(y) * w + x) * 4);
            m_pending.push_back({sm->second, Base() + m_stagingUsed});
            m_stagingUsed += (bytes + 255) & ~size_t(255);
            it = m_refillSlots.erase(it);
        }
    }

    // Debug readback: level 0 of one region present BOTH as a layer and as its own image, copied to a
    // host buffer (layer 256x256 then image w x h). Call RecordReadback(cmd) then, after the fence,
    // WriteReadback(dir). Returns false if no region is in both maps.
    bool RecordReadback(VkCommandBuffer cmd, int pick = 1) {
        int seen = 0;
        for (auto& kv : m_layerMap) {
            auto it = m_map.find(kv.first);
            if (it == m_map.end()) continue;
            const Entry& e = m_slots[it->second];
            if (pick >= 100) { if (kv.second != uint32_t(pick - 100)) continue; }                // exact layer
            else if (pick >= 2 && (e.w == kLayerSize && e.h == kLayerSize)) continue;   // want a tiled (smaller) region
            if (pick < 100 && ++seen < pick - 1) continue;
            m_rbLayer = kv.second; m_rbW = e.w; m_rbH = e.h; m_rbKey = kv.first;
            const VkDeviceSize bytes = VkDeviceSize(kLayerSize) * kLayerSize * 4 + VkDeviceSize(e.w) * e.h * 4;
            if (m_rbBuf == VK_NULL_HANDLE) {
                VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};
                bi.size = VkDeviceSize(kLayerSize) * kLayerSize * 4 * 2; bi.usage = VK_BUFFER_USAGE_TRANSFER_DST_BIT;
                vkCreateBuffer(m_dev, &bi, nullptr, &m_rbBuf);
                VkMemoryRequirements req{}; vkGetBufferMemoryRequirements(m_dev, m_rbBuf, &req);
                m_alloc->Allocate(req, &m_rbMem);
                vkBindBufferMemory(m_dev, m_rbBuf, m_rbMem, 0);
            }
            (void)bytes;
            auto toSrc = [&](VkImage img, uint32_t layer, VkImageLayout from, VkImageLayout to) {
                VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
                b.srcAccessMask = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT; b.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_SHADER_READ_BIT;
                b.oldLayout = from; b.newLayout = to;
                b.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED; b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
                b.image = img; b.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, layer, 1};
                vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, 0, 0, nullptr, 0, nullptr, 1, &b);
            };
            toSrc(m_array.image, m_rbLayer, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL);
            toSrc(e.image, 0, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL);
            VkBufferImageCopy r{};
            r.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, m_rbLayer, 1};
            r.imageExtent = {kLayerSize, kLayerSize, 1};
            vkCmdCopyImageToBuffer(cmd, m_array.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, m_rbBuf, 1, &r);
            VkBufferImageCopy r2{};
            r2.bufferOffset = VkDeviceSize(kLayerSize) * kLayerSize * 4;
            r2.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
            r2.imageExtent = {e.w, e.h, 1};
            vkCmdCopyImageToBuffer(cmd, e.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, m_rbBuf, 1, &r2);
            toSrc(m_array.image, m_rbLayer, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
            toSrc(e.image, 0, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
            return true;
        }
        return false;
    }
    void WriteReadback(const std::string& dir) {
        uint8_t* p = nullptr;
        if (vkMapMemory(m_dev, m_rbMem, 0, VK_WHOLE_SIZE, 0, reinterpret_cast<void**>(&p)) != VK_SUCCESS) return;
        auto ppm = [&](const std::string& path, const uint8_t* px, uint32_t w, uint32_t h) {
            FILE* f = std::fopen(path.c_str(), "wb");
            if (!f) return;
            std::fprintf(f, "P6\n%u %u\n255\n", w, h);
            for (uint32_t i = 0; i < w * h; ++i) std::fwrite(px + i * 4, 1, 3, f);
            std::fclose(f);
        };
        ppm(dir + "/rb-layer.ppm", p, kLayerSize, kLayerSize);
        ppm(dir + "/rb-image.ppm", p + size_t(kLayerSize) * kLayerSize * 4, m_rbW, m_rbH);
        vkUnmapMemory(m_dev, m_rbMem);
        Log::Write(Log::Level::Info, Fmt("TCVR_RB region key=%llx layer=%u image %ux%u written to %s",
                                         (unsigned long long)m_rbKey, m_rbLayer, m_rbW, m_rbH, dir.c_str()));
    }

    // Colour table, 64 (luma) x 32 (5-bit component) RGBA8: texel.r/g/b = gamma(colorxlat) of the
    // red / green / blue channel for that component and luma. Rebuilt by the caller when the
    // board's tables change; uploaded at the next Flush.
    void SetLut(const uint8_t* rgba) {
        if (m_stagingUsed + 64 * 32 * 4 > kHalfBytes) return;
        std::memcpy(m_stagingPtr + Base() + m_stagingUsed, rgba, 64 * 32 * 4);
        m_lutOffset = Base() + m_stagingUsed;
        m_lutPending = true;
        m_stagingUsed += 64 * 32 * 4;
    }
    VkImageView LutView() const { return m_lut.view; }

    // Record uploads + mip chains of the regions created this frame. Call before the render pass.
    void Flush(VkCommandBuffer cmd) {
        if (m_arrayInit) {   // every layer valid to bind from the first frame (unused ones hold garbage, never sampled)
            VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
            b.srcAccessMask = 0; b.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
            b.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED; b.newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
            b.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED; b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
            b.image = m_array.image; b.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, m_array.levels, 0, kMaxLayers};
            vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, 0, 0, nullptr, 0, nullptr, 1, &b);
            m_arrayInit = false;
        }
        if (m_lutPending) { Upload(cmd, m_lut, m_lutOffset); m_lutPending = false; }
        if (m_dummyPending) {
            std::memset(m_stagingPtr + Base() + m_stagingUsed, 0, 4);
            Upload(cmd, m_dummy, Base() + m_stagingUsed);
            m_stagingUsed += 256;
            m_dummyPending = false;
        }
        for (auto& p : m_pending) Upload(cmd, m_slots[p.slot], p.offset);
        for (auto& p : m_pendingLayers) UploadLayer(cmd, p.slot, p.offset);
        m_pendingLayers.clear();
        if (!m_pending.empty()) m_created += uint32_t(m_pending.size());
        m_pending.clear();
        m_stagingUsed = 0;
    }

    // Descriptor writes for binding `imgBinding` (texture2D[kMaxSlots]) and `smpBinding`
    // (sampler[4]) of `set`: everything the first time / after Clear, then only new slots.
    void WriteDescriptors(VkDescriptorSet set, uint32_t imgBinding, uint32_t smpBinding, bool full,
                          const std::vector<uint32_t>& slots) {
        std::vector<VkDescriptorImageInfo> infos;
        std::vector<VkWriteDescriptorSet> writes;
        if (full) {
            infos.resize(kMaxSlots);
            for (uint32_t i = 0; i < kMaxSlots; ++i)
                infos[i] = {VK_NULL_HANDLE, (i < m_slots.size() ? m_slots[i].view : m_dummy.view), VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};
            VkWriteDescriptorSet w{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
            w.dstSet = set; w.dstBinding = imgBinding; w.dstArrayElement = 0;
            w.descriptorCount = kMaxSlots; w.descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE;
            w.pImageInfo = infos.data();
            writes.push_back(w);
            VkDescriptorImageInfo smp[8];
            for (int m = 0; m < 8; ++m) smp[m] = {m_samplers[m], VK_NULL_HANDLE, VK_IMAGE_LAYOUT_UNDEFINED};
            VkWriteDescriptorSet ws{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
            ws.dstSet = set; ws.dstBinding = smpBinding; ws.descriptorCount = 8;
            ws.descriptorType = VK_DESCRIPTOR_TYPE_SAMPLER; ws.pImageInfo = smp;
            writes.push_back(ws);
            VkDescriptorImageInfo lut{m_lutSampler, m_lut.view, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};
            VkWriteDescriptorSet wl{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
            wl.dstSet = set; wl.dstBinding = 14; wl.descriptorCount = 1;
            wl.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER; wl.pImageInfo = &lut;
            writes.push_back(wl);
            VkDescriptorImageInfo arr{m_arraySampler, m_array.view, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};
            VkWriteDescriptorSet wa{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
            wa.dstSet = set; wa.dstBinding = 15; wa.descriptorCount = 1;
            wa.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER; wa.pImageInfo = &arr;
            writes.push_back(wa);
            vkUpdateDescriptorSets(m_dev, uint32_t(writes.size()), writes.data(), 0, nullptr);
            return;
        }
        if (slots.empty()) return;
        infos.resize(slots.size());
        for (size_t i = 0; i < slots.size(); ++i) {
            if (slots[i] >= m_slots.size()) continue;
            infos[i] = {VK_NULL_HANDLE, m_slots[slots[i]].view, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};
            VkWriteDescriptorSet w{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
            w.dstSet = set; w.dstBinding = imgBinding; w.dstArrayElement = slots[i];
            w.descriptorCount = 1; w.descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE;
            w.pImageInfo = &infos[i];
            writes.push_back(w);
        }
        vkUpdateDescriptorSets(m_dev, uint32_t(writes.size()), writes.data(), 0, nullptr);
    }
    std::vector<uint32_t> TakeDirty() { std::vector<uint32_t> d; d.swap(m_dirtySlots); return d; }
    // Staging half follows the frame slot being recorded (its previous use is fenced).
    void SetHalf(uint32_t h) { if (h != m_half) { m_half = h & 1u; m_stagingUsed = 0; } }
    // After all sets were written for this frame.
    void DescriptorsDone() { m_dirtySlots.clear(); m_resetDescriptors = false; }
    bool NeedsFullDescriptorWrite() const { return m_resetDescriptors; }
    bool HasDirty() const { return !m_dirtySlots.empty(); }
    uint32_t Count() const { return uint32_t(m_slots.size()); }
    uint32_t Created() const { return m_created; }

private:
    struct Entry {
        VkImage image = VK_NULL_HANDLE;
        VkDeviceMemory mem = VK_NULL_HANDLE;
        VkImageView view = VK_NULL_HANDLE;
        uint32_t w = 0, h = 0, levels = 0;
    };
    struct Pending { uint32_t slot; size_t offset; };

    Entry CreateImage(uint32_t w, uint32_t h, uint32_t levels) {
        Entry e;
        e.w = w; e.h = h; e.levels = levels;
        VkImageCreateInfo ii{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};
        ii.imageType = VK_IMAGE_TYPE_2D;
        ii.format = VK_FORMAT_R8G8B8A8_UNORM;
        ii.extent = {w, h, 1};
        ii.mipLevels = levels;
        ii.arrayLayers = 1;
        ii.samples = VK_SAMPLE_COUNT_1_BIT;
        ii.tiling = VK_IMAGE_TILING_OPTIMAL;
        ii.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
        ii.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        XRC_CHECK_THROW_VKCMD(vkCreateImage(m_dev, &ii, nullptr, &e.image));
        VkMemoryRequirements req{};
        vkGetImageMemoryRequirements(m_dev, e.image, &req);
        m_alloc->Allocate(req, &e.mem, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
        XRC_CHECK_THROW_VKCMD(vkBindImageMemory(m_dev, e.image, e.mem, 0));
        VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};
        vi.image = e.image;
        vi.viewType = VK_IMAGE_VIEW_TYPE_2D;
        vi.format = VK_FORMAT_R8G8B8A8_UNORM;
        vi.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, levels, 0, 1};
        XRC_CHECK_THROW_VKCMD(vkCreateImageView(m_dev, &vi, nullptr, &e.view));
        return e;
    }

    void CreateArray() {
        uint32_t levels = 1;
        while ((kLayerSize >> levels) > 0) ++levels;
        VkImageCreateInfo ii{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};
        ii.imageType = VK_IMAGE_TYPE_2D; ii.format = VK_FORMAT_R8G8B8A8_UNORM;
        ii.extent = {kLayerSize, kLayerSize, 1}; ii.mipLevels = levels; ii.arrayLayers = kMaxLayers;
        ii.samples = VK_SAMPLE_COUNT_1_BIT; ii.tiling = VK_IMAGE_TILING_OPTIMAL;
        ii.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
        ii.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        XRC_CHECK_THROW_VKCMD(vkCreateImage(m_dev, &ii, nullptr, &m_array.image));
        VkMemoryRequirements req{};
        vkGetImageMemoryRequirements(m_dev, m_array.image, &req);
        m_alloc->Allocate(req, &m_array.mem, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
        XRC_CHECK_THROW_VKCMD(vkBindImageMemory(m_dev, m_array.image, m_array.mem, 0));
        VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};
        vi.image = m_array.image; vi.viewType = VK_IMAGE_VIEW_TYPE_2D_ARRAY; vi.format = VK_FORMAT_R8G8B8A8_UNORM;
        vi.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, levels, 0, kMaxLayers};
        XRC_CHECK_THROW_VKCMD(vkCreateImageView(m_dev, &vi, nullptr, &m_array.view));
        m_array.w = kLayerSize; m_array.h = kLayerSize; m_array.levels = levels;
        VkSamplerCreateInfo si{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};
        si.magFilter = VK_FILTER_LINEAR; si.minFilter = VK_FILTER_LINEAR; si.mipmapMode = VK_SAMPLER_MIPMAP_MODE_LINEAR;
        si.addressModeU = si.addressModeV = VK_SAMPLER_ADDRESS_MODE_REPEAT;
        si.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
        si.anisotropyEnable = m_maxAniso > 1.0f ? VK_TRUE : VK_FALSE;
        si.maxAnisotropy = std::max(1.0f, m_maxAniso);
        si.maxLod = 16.0f;
        XRC_CHECK_THROW_VKCMD(vkCreateSampler(m_dev, &si, nullptr, &m_arraySampler));
        m_arrayInit = true;   // all layers still UNDEFINED: transitioned at the first Flush
    }

    void UploadLayer(VkCommandBuffer cmd, uint32_t layer, size_t offset) {
        auto bar = [&](uint32_t lvl, VkImageLayout from, VkImageLayout to, VkAccessFlags sa, VkAccessFlags da,
                       VkPipelineStageFlags ss, VkPipelineStageFlags ds) {
            VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
            b.srcAccessMask = sa; b.dstAccessMask = da; b.oldLayout = from; b.newLayout = to;
            b.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED; b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
            b.image = m_array.image; b.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, lvl, 1, layer, 1};
            vkCmdPipelineBarrier(cmd, ss, ds, 0, 0, nullptr, 0, nullptr, 1, &b);
        };
        for (uint32_t l = 0; l < m_array.levels; ++l)
            bar(l, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_ACCESS_SHADER_READ_BIT,
                VK_ACCESS_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
        VkBufferImageCopy r{};
        r.bufferOffset = offset;
        r.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, layer, 1};
        r.imageExtent = {kLayerSize, kLayerSize, 1};
        vkCmdCopyBufferToImage(cmd, m_staging, m_array.image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &r);
        int32_t w = int32_t(kLayerSize);
        for (uint32_t l = 1; l < m_array.levels; ++l) {
            bar(l - 1, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_ACCESS_TRANSFER_WRITE_BIT,
                VK_ACCESS_TRANSFER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
            VkImageBlit bl{};
            bl.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, l - 1, layer, 1};
            bl.srcOffsets[1] = {w, w, 1};
            const int32_t nw = std::max(1, w / 2);
            bl.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, l, layer, 1};
            bl.dstOffsets[1] = {nw, nw, 1};
            vkCmdBlitImage(cmd, m_array.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, m_array.image,
                           VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &bl, VK_FILTER_LINEAR);
            bar(l - 1, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_ACCESS_TRANSFER_READ_BIT,
                VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
            w = nw;
        }
        bar(m_array.levels - 1, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
            VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
            VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
    }

    void DestroyEntry(Entry& e) {
        if (e.view) vkDestroyImageView(m_dev, e.view, nullptr);
        if (e.image) vkDestroyImage(m_dev, e.image, nullptr);
        if (e.mem) vkFreeMemory(m_dev, e.mem, nullptr);
        e = Entry{};
    }

    static void Barrier(VkCommandBuffer cmd, VkImage img, uint32_t level, uint32_t count, VkImageLayout from, VkImageLayout to,
                        VkAccessFlags srcA, VkAccessFlags dstA, VkPipelineStageFlags srcS, VkPipelineStageFlags dstS) {
        VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
        b.srcAccessMask = srcA; b.dstAccessMask = dstA;
        b.oldLayout = from; b.newLayout = to;
        b.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED; b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        b.image = img;
        b.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, level, count, 0, 1};
        vkCmdPipelineBarrier(cmd, srcS, dstS, 0, 0, nullptr, 0, nullptr, 1, &b);
    }

    void Upload(VkCommandBuffer cmd, const Entry& e, size_t offset) {
        Barrier(cmd, e.image, 0, e.levels, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 0,
                VK_ACCESS_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
        VkBufferImageCopy r{};
        r.bufferOffset = offset;
        r.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
        r.imageExtent = {e.w, e.h, 1};
        vkCmdCopyBufferToImage(cmd, m_staging, e.image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &r);
        // Mip chain: box-filter each level from the previous one on the GPU.
        int32_t w = int32_t(e.w), h = int32_t(e.h);
        for (uint32_t l = 1; l < e.levels; ++l) {
            Barrier(cmd, e.image, l - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                    VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
                    VK_PIPELINE_STAGE_TRANSFER_BIT);
            VkImageBlit bl{};
            bl.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, l - 1, 0, 1};
            bl.srcOffsets[1] = {w, h, 1};
            const int32_t nw = std::max(1, w / 2), nh = std::max(1, h / 2);
            bl.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, l, 0, 1};
            bl.dstOffsets[1] = {nw, nh, 1};
            vkCmdBlitImage(cmd, e.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, e.image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &bl,
                           VK_FILTER_LINEAR);
            Barrier(cmd, e.image, l - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                    VK_ACCESS_TRANSFER_READ_BIT, VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
                    VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
            w = nw; h = nh;
        }
        Barrier(cmd, e.image, e.levels - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
                VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
    }

    VkDevice m_dev = VK_NULL_HANDLE;
    const MemoryAllocator* m_alloc = nullptr;
    VkSampler m_samplers[8] = {};
    VkSampler m_lutSampler = VK_NULL_HANDLE;
    VkBuffer m_staging = VK_NULL_HANDLE;
    VkDeviceMemory m_stagingMem = VK_NULL_HANDLE;
    uint8_t* m_stagingPtr = nullptr;
    size_t m_stagingUsed = 0;
    uint32_t m_half = 0;
    size_t Base() const { return size_t(m_half) * kHalfBytes; }
    Entry m_dummy;
    VkBuffer m_rbBuf = VK_NULL_HANDLE;
    VkDeviceMemory m_rbMem = VK_NULL_HANDLE;
    uint32_t m_rbLayer = 0, m_rbW = 0, m_rbH = 0;
    uint64_t m_rbKey = 0;
    Entry m_array;
    VkSampler m_arraySampler = VK_NULL_HANDLE;
    bool m_arrayInit = false;
    float m_maxAniso = 1.0f;
    uint32_t m_layerCount = 0;
    std::unordered_map<uint64_t, uint32_t> m_layerMap;
    std::vector<Pending> m_pendingLayers;
    Entry m_lut;
    size_t m_lutOffset = 0;
    bool m_lutPending = false;
    bool m_dummyPending = false;
    std::vector<Entry> m_slots;
    std::unordered_map<uint64_t, uint32_t> m_map;
    std::vector<Pending> m_pending;
    std::vector<uint32_t> m_dirtySlots;
    std::set<uint64_t> m_refillSlots, m_refillLayers;
    bool m_resetDescriptors = true;
    uint32_t m_created = 0;
};

}  // namespace arcadexr::vulkan
