#pragma once

// Every Model 2 texture region becomes a real GPU texture (opus55, 22/09/2026).
//
// The board keeps all its textures in two 2048x1024 sheets of 4-bit texels. Sampled from the
// sheet, the texture unit can neither repeat a tile on itself (the road), nor use mipmaps, nor
// filter anisotropically: the shader had to redo it by hand, and that was the single biggest
// cost of a pixel (measured: +4 ms of ~9 ms, both eyes, 1680x1760, MSAA 4x).
//
// Here each region (sheet, x, y, w, h) that a polygon uses gets its own VkImage with a full mip
// chain generated by the GPU, sampled with REPEAT / MIRRORED_REPEAT and hardware anisotropy,
// all indexed from ONE descriptor array by a per-polygon slot (VK_EXT_descriptor_indexing).
//
// What is stored is NOT a colour: it is the raw texel t (and, for cut-outs, t premultiplied by
// opacity plus the opacity). The polygon's palette / tone curve is applied AFTER filtering, in
// the shader, exactly like the board -- so one image per texture, whatever palette uses it.
//   R = t*17            (opaque use: t = R*15)
//   G = t*17 * opaque   B = 255 * opaque   (cut-out use: t = G/B*15, alpha = B), opaque = t != 15
//
// Texture RAM is static during a race (measured: 0 writes after loading), so a region is built
// once and kept until the sheets change.

#include <vulkan/vulkan.h>
#include <unordered_map>
#include <vector>
#include <cstring>
#include <algorithm>

#include "vulkan_utils.h"

namespace arcadexr::vulkan {

class M2RegionTextures {
public:
    static constexpr uint32_t kMaxSlots = 512;
    static constexpr uint32_t kNone = 0xffffu;
    static constexpr uint32_t kStagingBytes = 16u * 1024u * 1024u;

    void Init(VkDevice device, const MemoryAllocator* alloc, float maxAniso) {
        m_dev = device;
        m_alloc = alloc;
        for (int m = 0; m < 4; ++m) {
            VkSamplerCreateInfo si{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};
            si.magFilter = VK_FILTER_LINEAR;
            si.minFilter = VK_FILTER_LINEAR;
            si.mipmapMode = VK_SAMPLER_MIPMAP_MODE_LINEAR;
            si.addressModeU = (m & 1) ? VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT : VK_SAMPLER_ADDRESS_MODE_REPEAT;
            si.addressModeV = (m & 2) ? VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT : VK_SAMPLER_ADDRESS_MODE_REPEAT;
            si.addressModeW = VK_SAMPLER_ADDRESS_MODE_REPEAT;
            si.anisotropyEnable = maxAniso > 1.0f ? VK_TRUE : VK_FALSE;
            si.maxAnisotropy = std::max(1.0f, maxAniso);
            si.minLod = 0.0f;
            si.maxLod = 16.0f;
            XRC_CHECK_THROW_VKCMD(vkCreateSampler(m_dev, &si, nullptr, &m_samplers[m]));
        }
        // Staging, host visible, reused every frame (the previous frame's copies are fenced).
        VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};
        bi.size = kStagingBytes;
        bi.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
        XRC_CHECK_THROW_VKCMD(vkCreateBuffer(m_dev, &bi, nullptr, &m_staging));
        VkMemoryRequirements req{};
        vkGetBufferMemoryRequirements(m_dev, m_staging, &req);
        m_alloc->Allocate(req, &m_stagingMem);
        XRC_CHECK_THROW_VKCMD(vkBindBufferMemory(m_dev, m_staging, m_stagingMem, 0));
        XRC_CHECK_THROW_VKCMD(vkMapMemory(m_dev, m_stagingMem, 0, kStagingBytes, 0, reinterpret_cast<void**>(&m_stagingPtr)));
        // Dummy 1x1 image for every empty slot (no partially-bound descriptors needed).
        m_dummy = CreateImage(1, 1, 1);
        m_dummyPending = true;
    }

    void Destroy() {
        if (m_dev == VK_NULL_HANDLE) return;
        Clear();
        DestroyEntry(m_dummy);
        for (auto& s : m_samplers) if (s) { vkDestroySampler(m_dev, s, nullptr); s = VK_NULL_HANDLE; }
        if (m_stagingPtr) { vkUnmapMemory(m_dev, m_stagingMem); m_stagingPtr = nullptr; }
        if (m_staging) vkDestroyBuffer(m_dev, m_staging, nullptr);
        if (m_stagingMem) vkFreeMemory(m_dev, m_stagingMem, nullptr);
        m_staging = VK_NULL_HANDLE; m_stagingMem = VK_NULL_HANDLE;
        m_dev = VK_NULL_HANDLE;
    }

    // Drop every region (the sheets changed). Caller guarantees the GPU is idle on them.
    void Clear() {
        for (auto& e : m_slots) DestroyEntry(e);
        m_slots.clear();
        m_map.clear();
        m_pending.clear();
        m_dirtySlots.clear();
        m_resetDescriptors = true;
    }

    // Slot of a region, creating it (this frame, within the staging budget) if new.
    // Returns kNone while it is not ready -- the shader then takes the sheet path.
    uint32_t Slot(const std::vector<uint8_t>* sheets, uint32_t sheet, uint32_t ox, uint32_t oy, uint32_t w, uint32_t h) {
        if (w < 1 || h < 1 || w > 1024 || h > 1024 || sheets[sheet & 1].empty()) return kNone;
        const uint64_t key = (uint64_t(sheet & 1) << 60) | (uint64_t(ox) << 44) | (uint64_t(oy) << 28) | (uint64_t(w) << 14) | uint64_t(h);
        auto it = m_map.find(key);
        if (it != m_map.end()) return it->second;
        if (m_slots.size() >= kMaxSlots) return kNone;
        const size_t bytes = size_t(w) * h * 4;
        if (m_stagingUsed + bytes > kStagingBytes) return kNone;  // next frame
        // Texels of the region, through the board's fold (x >= 1024 -> other half).
        uint8_t* dst = m_stagingPtr + m_stagingUsed;
        const std::vector<uint8_t>& cpu = sheets[sheet & 1];
        for (uint32_t y = 0; y < h; ++y)
            for (uint32_t x = 0; x < w; ++x) {
                int x2 = int(ox + x), y2 = int(oy + y);
                if (x2 >= 1024) { x2 -= 1024; y2 ^= 1024; }
                const size_t at = size_t(y2) * 1024 + size_t(x2);
                const uint8_t t = at < cpu.size() ? cpu[at] : 0;
                const bool opaque = t != 15;
                uint8_t* px = dst + (size_t(y) * w + x) * 4;
                px[0] = uint8_t(t * 17);
                px[1] = opaque ? uint8_t(t * 17) : 0;
                px[2] = opaque ? 255 : 0;
                px[3] = 255;
            }
        uint32_t levels = 1;
        while ((std::max(w, h) >> levels) > 0) ++levels;
        Entry e = CreateImage(w, h, levels);
        const uint32_t slot = uint32_t(m_slots.size());
        m_slots.push_back(e);
        m_map.emplace(key, slot);
        m_pending.push_back({slot, m_stagingUsed});
        m_dirtySlots.push_back(slot);
        m_stagingUsed += (bytes + 255) & ~size_t(255);
        return slot;
    }

    // Record uploads + mip chains of the regions created this frame. Call before the render pass.
    void Flush(VkCommandBuffer cmd) {
        if (m_dummyPending) {
            std::memset(m_stagingPtr + m_stagingUsed, 0, 4);
            Upload(cmd, m_dummy, m_stagingUsed);
            m_stagingUsed += 256;
            m_dummyPending = false;
        }
        for (auto& p : m_pending) Upload(cmd, m_slots[p.slot], p.offset);
        if (!m_pending.empty()) m_created += uint32_t(m_pending.size());
        m_pending.clear();
        m_stagingUsed = 0;
    }

    // Descriptor writes for binding `imgBinding` (texture2D[kMaxSlots]) and `smpBinding`
    // (sampler[4]) of `set`: everything the first time / after Clear, then only new slots.
    void WriteDescriptors(VkDescriptorSet set, uint32_t imgBinding, uint32_t smpBinding, bool full) {
        std::vector<VkDescriptorImageInfo> infos;
        std::vector<VkWriteDescriptorSet> writes;
        if (full) {
            infos.resize(kMaxSlots);
            for (uint32_t i = 0; i < kMaxSlots; ++i)
                infos[i] = {VK_NULL_HANDLE, (i < m_slots.size() ? m_slots[i].view : m_dummy.view), VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};
            VkWriteDescriptorSet w{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
            w.dstSet = set; w.dstBinding = imgBinding; w.dstArrayElement = 0;
            w.descriptorCount = kMaxSlots; w.descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE;
            w.pImageInfo = infos.data();
            writes.push_back(w);
            VkDescriptorImageInfo smp[4];
            for (int m = 0; m < 4; ++m) smp[m] = {m_samplers[m], VK_NULL_HANDLE, VK_IMAGE_LAYOUT_UNDEFINED};
            VkWriteDescriptorSet ws{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
            ws.dstSet = set; ws.dstBinding = smpBinding; ws.descriptorCount = 4;
            ws.descriptorType = VK_DESCRIPTOR_TYPE_SAMPLER; ws.pImageInfo = smp;
            writes.push_back(ws);
            vkUpdateDescriptorSets(m_dev, uint32_t(writes.size()), writes.data(), 0, nullptr);
            return;
        }
        if (m_dirtySlots.empty()) return;
        infos.resize(m_dirtySlots.size());
        for (size_t i = 0; i < m_dirtySlots.size(); ++i) {
            infos[i] = {VK_NULL_HANDLE, m_slots[m_dirtySlots[i]].view, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};
            VkWriteDescriptorSet w{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
            w.dstSet = set; w.dstBinding = imgBinding; w.dstArrayElement = m_dirtySlots[i];
            w.descriptorCount = 1; w.descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE;
            w.pImageInfo = &infos[i];
            writes.push_back(w);
        }
        vkUpdateDescriptorSets(m_dev, uint32_t(writes.size()), writes.data(), 0, nullptr);
    }
    // After all sets were written for this frame.
    void DescriptorsDone() { m_dirtySlots.clear(); m_resetDescriptors = false; }
    bool NeedsFullDescriptorWrite() const { return m_resetDescriptors; }
    bool HasDirty() const { return !m_dirtySlots.empty(); }
    uint32_t Count() const { return uint32_t(m_slots.size()); }
    uint32_t Created() const { return m_created; }

private:
    struct Entry {
        VkImage image = VK_NULL_HANDLE;
        VkDeviceMemory mem = VK_NULL_HANDLE;
        VkImageView view = VK_NULL_HANDLE;
        uint32_t w = 0, h = 0, levels = 0;
    };
    struct Pending { uint32_t slot; size_t offset; };

    Entry CreateImage(uint32_t w, uint32_t h, uint32_t levels) {
        Entry e;
        e.w = w; e.h = h; e.levels = levels;
        VkImageCreateInfo ii{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};
        ii.imageType = VK_IMAGE_TYPE_2D;
        ii.format = VK_FORMAT_R8G8B8A8_UNORM;
        ii.extent = {w, h, 1};
        ii.mipLevels = levels;
        ii.arrayLayers = 1;
        ii.samples = VK_SAMPLE_COUNT_1_BIT;
        ii.tiling = VK_IMAGE_TILING_OPTIMAL;
        ii.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
        ii.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        XRC_CHECK_THROW_VKCMD(vkCreateImage(m_dev, &ii, nullptr, &e.image));
        VkMemoryRequirements req{};
        vkGetImageMemoryRequirements(m_dev, e.image, &req);
        m_alloc->Allocate(req, &e.mem, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
        XRC_CHECK_THROW_VKCMD(vkBindImageMemory(m_dev, e.image, e.mem, 0));
        VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};
        vi.image = e.image;
        vi.viewType = VK_IMAGE_VIEW_TYPE_2D;
        vi.format = VK_FORMAT_R8G8B8A8_UNORM;
        vi.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, levels, 0, 1};
        XRC_CHECK_THROW_VKCMD(vkCreateImageView(m_dev, &vi, nullptr, &e.view));
        return e;
    }

    void DestroyEntry(Entry& e) {
        if (e.view) vkDestroyImageView(m_dev, e.view, nullptr);
        if (e.image) vkDestroyImage(m_dev, e.image, nullptr);
        if (e.mem) vkFreeMemory(m_dev, e.mem, nullptr);
        e = Entry{};
    }

    static void Barrier(VkCommandBuffer cmd, VkImage img, uint32_t level, uint32_t count, VkImageLayout from, VkImageLayout to,
                        VkAccessFlags srcA, VkAccessFlags dstA, VkPipelineStageFlags srcS, VkPipelineStageFlags dstS) {
        VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
        b.srcAccessMask = srcA; b.dstAccessMask = dstA;
        b.oldLayout = from; b.newLayout = to;
        b.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED; b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        b.image = img;
        b.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, level, count, 0, 1};
        vkCmdPipelineBarrier(cmd, srcS, dstS, 0, 0, nullptr, 0, nullptr, 1, &b);
    }

    void Upload(VkCommandBuffer cmd, const Entry& e, size_t offset) {
        Barrier(cmd, e.image, 0, e.levels, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 0,
                VK_ACCESS_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
        VkBufferImageCopy r{};
        r.bufferOffset = offset;
        r.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
        r.imageExtent = {e.w, e.h, 1};
        vkCmdCopyBufferToImage(cmd, m_staging, e.image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &r);
        // Mip chain: box-filter each level from the previous one on the GPU.
        int32_t w = int32_t(e.w), h = int32_t(e.h);
        for (uint32_t l = 1; l < e.levels; ++l) {
            Barrier(cmd, e.image, l - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                    VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
                    VK_PIPELINE_STAGE_TRANSFER_BIT);
            VkImageBlit bl{};
            bl.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, l - 1, 0, 1};
            bl.srcOffsets[1] = {w, h, 1};
            const int32_t nw = std::max(1, w / 2), nh = std::max(1, h / 2);
            bl.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, l, 0, 1};
            bl.dstOffsets[1] = {nw, nh, 1};
            vkCmdBlitImage(cmd, e.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, e.image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &bl,
                           VK_FILTER_LINEAR);
            Barrier(cmd, e.image, l - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                    VK_ACCESS_TRANSFER_READ_BIT, VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
                    VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
            w = nw; h = nh;
        }
        Barrier(cmd, e.image, e.levels - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
                VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
    }

    VkDevice m_dev = VK_NULL_HANDLE;
    const MemoryAllocator* m_alloc = nullptr;
    VkSampler m_samplers[4] = {};
    VkBuffer m_staging = VK_NULL_HANDLE;
    VkDeviceMemory m_stagingMem = VK_NULL_HANDLE;
    uint8_t* m_stagingPtr = nullptr;
    size_t m_stagingUsed = 0;
    Entry m_dummy;
    bool m_dummyPending = false;
    std::vector<Entry> m_slots;
    std::unordered_map<uint64_t, uint32_t> m_map;
    std::vector<Pending> m_pending;
    std::vector<uint32_t> m_dirtySlots;
    bool m_resetDescriptors = true;
    uint32_t m_created = 0;
};

}  // namespace arcadexr::vulkan
